// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	jwt "github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"
)

// JwtGenerator is an autogenerated mock type for the JwtGenerator type
type JwtGenerator struct {
	mock.Mock
}

// GenerateJWTToken provides a mock function with given fields: claims
func (_m *JwtGenerator) GenerateJWTToken(claims jwt.MapClaims) (string, error) {
	ret := _m.Called(claims)

	if len(ret) == 0 {
		panic("no return value specified for GenerateJWTToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(jwt.MapClaims) (string, error)); ok {
		return rf(claims)
	}
	if rf, ok := ret.Get(0).(func(jwt.MapClaims) string); ok {
		r0 = rf(claims)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(jwt.MapClaims) error); ok {
		r1 = rf(claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJwtGenerator creates a new instance of JwtGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJwtGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *JwtGenerator {
	mock := &JwtGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
