.PHONY: run swagger-gen

# ========================
# Variables
# ========================
GO_TEST := go test
GO_TEST_ARGS := -v -cover

# ========================
# Run app
# ========================
run:swagger-gen
	go run ./cmd/api/main.go
# ========================
# Run app
# ========================
swagger-gen:
	swag init -g ./cmd/api/main.go --output ./docs
# ========================
# Unit tests
# ========================

# Run single test function
test-unit-one:
ifndef t
	$(error ❌ Missing test name: use t=<NameOfTest>)
endif
ifndef folder
	$(error ❌ Missing package path: use folder=./internal/...)
endif
	$(GO_TEST) $(GO_TEST_ARGS) -run $(t) $(folder)

# Run all tests in a package
test-unit-all:
ifndef folder
	$(error ❌ Missing package path: use folder=./internal/...)
endif
	$(GO_TEST) $(GO_TEST_ARGS) $(folder)
# ========================
# Mock generation
# ========================

# Generate mock trong 1 package cụ thể
# Usage: make mock-one folder=./internal/service
mock-one:
ifndef folder
	$(error ❌ Missing folder: use folder=./internal/...)
endif
	@echo "→ Generating mocks in $(folder)..."
	cd $(folder) && go generate ./...

# Generate toàn bộ mock trong project
# Usage: make mock-all
mock-all:
	@echo "→ Generating all mocks..."
	go generate ./...