.PHONY: run swagger-gen

# ========================
# Variables
# ========================
GO_TEST := go test
GO_TEST_ARGS := -v -cover

# ========================
# Run app
# ========================
run:swagger-gen
	go run ./cmd/api/main.go
# ========================
# Run app
# ========================
swagger-gen:
	swag init -g ./cmd/api/main.go --output ./docs
# ========================
# Unit tests
# ========================

# Run single test function
test-one:
ifndef t
	$(error ❌ Missing test name: use t=<NameOfTest>)
endif
ifndef folder
	$(error ❌ Missing package path: use folder=./internal/...)
endif
	$(GO_TEST) $(GO_TEST_ARGS) -run $(t) $(folder)

# Run all tests in a package
test-all:
ifndef folder
	$(error ❌ Missing package path: use folder=./internal/...)
endif
	$(GO_TEST) $(GO_TEST_ARGS) $(folder)
# ========================
# Mock generation
# ========================

# Generate mock trong 1 package cụ thể
# Usage: make mock-one folder=./internal/service
mock-one:
ifndef folder
	$(error ❌ Missing folder: use folder=./internal/...)
endif
	@echo "→ Generating mocks in $(folder)..."
	cd $(folder) && go generate ./...

# Generate toàn bộ mock trong project
# Usage: make mock-all
mock-all:
	@echo "→ Generating all mocks..."
	go generate ./...

# ========================
# Docker login
# ========================
docker-login:
	docker login
# ========================
# Docker hub image build
# ========================
docker-build: swagger-gen
ifndef name
	$(error ❌ Missing image name: use name=<Name Of Image>)
endif
ifndef tag
	$(error ❌ Missing tag: use tag=<Name of Tag image>)
endif
	docker build -t $(name):$(tag) .
# ========================
# Docker hub image push
# ========================
docker-release:
ifndef name
	$(error ❌ Missing image name: use name=<Name Of Image>)
endif
ifndef tag
	$(error ❌ Missing tag: use tag=<Name of Tag image>)
endif
	docker push $(name):$(tag)

# ========================
# Coverage
# ========================
COVERAGE_EXCLUDE=infrastructure|mocks|test|docs|main.go|config.go|client.go
COVERAGE_THRESHOLD = 80
COVERAGE_FOLDER=./coverage
clean:
	go clean -testcache
	rm -rf $(COVERAGE_FOLDER)
# 	docker rm -f redis || true
test: clean
	mkdir -p $(COVERAGE_FOLDER)
	go test ./... -coverprofile=$(COVERAGE_FOLDER)/coverage.tmp -covermode=atomic -coverpkg=./... -p 1
	grep -v -E "$(COVERAGE_EXCLUDE)" $(COVERAGE_FOLDER)/coverage.tmp > $(COVERAGE_FOLDER)/coverage.out
	go tool cover -html=$(COVERAGE_FOLDER)/coverage.out -o $(COVERAGE_FOLDER)/coverage.html
	@total=$$(go tool cover -func=$(COVERAGE_FOLDER)/coverage.out | grep total: | awk '{print $$3}' | sed 's/%//'); \
    if [ $$(echo "$$total < $(COVERAGE_THRESHOLD)" | bc -l) -eq 1 ]; then \
	   echo "❌ Coverage ($$total%) is below threshold ($(COVERAGE_THRESHOLD)%)"; \
	   exit 1; \
    else \
	   echo "✅ Coverage ($$total%) meets threshold ($(COVERAGE_THRESHOLD)%)"; \
   	fi