// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetLink provides a mock function with given fields: ctx, code
func (_m *Service) GetLink(ctx context.Context, code string) (string, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetLink")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShortenLink provides a mock function with given fields: ctx, url, codeLength, exptime
func (_m *Service) ShortenLink(ctx context.Context, url string, codeLength int, exptime int64) (string, error) {
	ret := _m.Called(ctx, url, codeLength, exptime)

	if len(ret) == 0 {
		panic("no return value specified for ShortenLink")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int64) (string, error)); ok {
		return rf(ctx, url, codeLength, exptime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int64) string); ok {
		r0 = rf(ctx, url, codeLength, exptime)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int64) error); ok {
		r1 = rf(ctx, url, codeLength, exptime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
