version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  app:
    image: app-api:latest
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: app-api
    env_file:
      - ../.env
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - APP_PORT=8081
      - REDIS_ADDR=redis:6379
      - APP_HOST=localhost/api

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:z
    depends_on:
      - app