upstream app {
    server app:8080;
}

upstream portal {
    server portal:3000;
}

server {
    listen 80;
    listen [::]:80;
    server_name _;

    # =========================
    # 1. Short link → backend
    # =========================
    location ~ "^/([a-zA-Z0-9]{6,7})$" {
        if ($request_method = GET) {
            proxy_pass http://app/v1/links/redirect/$1;
        }
    }  

    # =========================
    # 2. API → backend
    # =========================
    location /api/bookmark_service/ {
        proxy_pass http://app/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # =========================
    # 3. Frontend → portal
    # =========================
    location / {
        proxy_pass http://portal/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}